### ISSUE TITLE
Use npm WMI module?

### ISSUE THREAD

**Issue by lurch** [resin-io-modules/drivelist#113]
So, from the little I've learned of Etcher so far, it seems the ideal situation is to try and move as much "native code" as possible into NodeJS libraries? To that end, would it be worth replacing the current `scripts/win32.bat` with a script using one of [these](https://www.npmjs.com/search?q=WMI) instead?
Or does that just end up shifting the native-code-dependency further down the stack?

**Comment by lurch** [comment]
I guess at the very least, maintaining JavaScript code has got to be easier than trying to maintain VBScript code ;-)

**Comment by jviotti** [comment]
Initially, the `drivelist` module was JavaScript only. It used several libraries similar to the one you pointed out, executed various child processes, etc; however, despite a bit counter-intuitive, the module got to a point where it was really unmaintainable. That situation led us to move all the code necessary to gather information from the system as platform scripts.

Turns out is much more natural to communicate with operating system tooling through Bash/batch scripts than by JavaScript (and add async code on top of that).

**Comment by lurch** [comment]
Fair enough, if it's a path you've already been down then feel free to close this issue.
