### ISSUE TITLE
Unable to list drives on my ubuntu since 5.0.0

### ISSUE THREAD

**Issue by VictorDubois** [resin-io-modules/drivelist#122]
Drivelist does not work on my PC since 5.0.0.
Config : Ubuntu 16.04, one HDD with ubuntu + windows

Error:

> [...]/node_modules/drivelist/scripts/linux.sh: ligne 93: UDEV_net.ifnames=0 : commande introuvable
>     at [...]/node_modules/drivelist/build/scripts.js:27:23
>     at ChildProcess.exithandler (child_process.js:204:7)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at maybeClose (internal/child_process.js:821:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

When running linux.sh:

> ./linux.sh 
> device: /dev/sda
> description: "WDC [...]"
> size: 1000204886016
> mountpoints:
>   - path: /
>   - path: /boot/efi
>   - path: /home
> raw: /dev/sda
> protected: False
> ./linux.sh: ligne 114: UDEV_net.ifnames=0 : commande introuvable
> system: True

('commande introuvable" = "command not found")

"UDEV_net.ifnames=0" is the last line returned by "udevadm info --query=property --export --export-prefix=UDEV_ --name=sda" (linux.sh, line 47).

**Comment by jviotti** [comment]
Hey there,

We've been investigating this and got to the bottom of it. The following
command:

    udevadm info --query=property --export --export-prefix=UDEV_ --name=sda

is supposed to output a collection of env vars we can evaluate in the
current script, in order to have access to information exposed by
`udev`.

In your setup, the following line is getting printed: 

    UDEV_net.ifnames=0

and since it contains a period on the variable name, is not interpreted
correctly by `bash`.

We'll be submitting a fix for this (probably a replacement of every
period in the variable names returned by `udevadm` by an underscore, or
something like that), but for the moment, you should be able to remove
the `net.ifnames=0` option (which is usually added to
`/etc/default/grub`), since `0` is the default value anyway as far as we
could see.

On Thu, Nov 17, 2016 at 04:55:14AM -0800, VictorDubois wrote:
> Drivelist does not work on my PC since 5.0.0.
> Config : Ubuntu 16.04, one HDD with ubuntu + windows
> 
> 
> Error:
> 
> > [...]/node_modules/drivelist/scripts/linux.sh: ligne 93: UDEV_net.ifnames=0 : commande introuvable
> >     at [...]/node_modules/drivelist/build/scripts.js:27:23
> >     at ChildProcess.exithandler (child_process.js:204:7)
> >     at emitTwo (events.js:87:13)
> >     at ChildProcess.emit (events.js:172:7)
> >     at maybeClose (internal/child_process.js:821:16)
> >     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 
> When running linux.sh:
> 
> > ./linux.sh 
> > device: /dev/sda
> > description: "WDC [...]"
> > size: 1000204886016
> > mountpoints:
> >   - path: /
> >   - path: /boot/efi
> >   - path: /home
> > raw: /dev/sda
> > protected: False
> > ./linux.sh: ligne 114: UDEV_net.ifnames=0 : commande introuvable
> > system: True
> 
> ('commande introuvable" = "command not found")
> 
> "UDEV_net.ifnames=0" is the last line returned by "udevadm info --query=property --export --export-prefix=UDEV_ --name=sda" (linux.sh, line 47).
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io-modules/drivelist/issues/122

-- 
Juan Cruz Viotti
Software Engineer

**Comment by jviotti** [comment]
Hi @VictorDubois ,

This issue has been fixed in v5.0.4. Let us know how that goes!

**Comment by VictorDubois** [comment]
It does work! Thank you for the quick fix :)
