### ISSUE TITLE
Removable Drive

### ISSUE THREAD

**Issue by othree** [resin-io-modules/drivelist#18]
Request for one more info, is drive removable?

For OSX, we can use `Ejectable` property.
For Windows, we can use [drive type](https://ardamis.com/2012/08/21/getting-a-list-of-logical-and-physical-drives-from-the-command-line/).
For Linux, `lsblk` have `RM` column.

**Comment by jviotti** [comment]
@othree Thanks for the extensive information, it's very appreciated!

I'll be travelling the next couple of days, but will take a closer look at this soon.

**Comment by jviotti** [comment]
I've did some research on this, and looking forward to implement soon. 

We're currently looking forward to build a set of scripts for each operating system that print all the information that we need in a predefined format instead of parsing the output of every command ourselves, which should allow us to have just one (simpler) parsing function and simplify the whole thing.

I prefer delaying the implementation of this feature until then in order to not duplicate any work, so I'll create a milestone for that and add this issue there.

**Comment by jviotti** [comment]
I've written an easy specification for the redesign in the wiki (https://github.com/resin-io/drivelist/wiki/Drivelist-redesign-spec). Feel free to comment and contribute!

**Comment by jviotti** [comment]
Closing this, since it was implemented as the `system` property. `system: false` means that the drive is removable.
