### ISSUE TITLE
[linux] Multiple partitions result in null mountpoint, description

### ISSUE THREAD

**Issue by Fordi** [resin-io-modules/drivelist#85]
For example, when examining an SD card being used as a system drive for something embedded, I get the following object:

```
{
    "device": "/dev/mmcblk0",
    "description": null,
    "size": 31914983424,
    "mountpoint": null,
    "name": "/dev/mmcblk0",
    "protected": false,
    "system": false
}
```

What I expect to see is more like: 

```
{
    "device": "/dev/mmcblk0p2",
    "size": "67108864",
    "mountpoint": null,
    "name": "/dev/mmcblk0p2",
    "protected": false,
    "system": false,
    "description": "system-boot"
},
{
    "device": "/dev/mmcblk0p3",
    "size": "1073741824",
    "mountpoint": "/media/rsi-bryan/system-a",
    "name": "/dev/mmcblk0p3",
    "protected": false,
    "system": false,
    "description": "system-a"
},
{
    "device": "/dev/mmcblk0p4",
    "size": "1073741824",
    "mountpoint": "/media/rsi-bryan/system-b",
    "name": "/dev/mmcblk0p4",
    "protected": false,
    "system": false,
    "description": "system-b"
},
{
    "device": "/dev/mmcblk0p5",
    "size": "1675624448",
    "mountpoint": "/media/rsi-bryan/writable",
    "name": "/dev/mmcblk0p5",
    "protected": false,
    "system": false,
    "description": "writable"
},
{
    "device": "/dev/mmcblk0p6",
    "size": "28015853568",
    "mountpoint": "/media/rsi-bryan/68C2-99CB",
    "name": "/dev/mmcblk0p6",
    "protected": false,
    "system": false,
    "description": "68C2-99CB"
}
```

Note that, on this SD card, mmcblk0p1 is a UEFI BIOS boot parititon, so it doesn't (and shouldn't) actually appear as a "drive".

The following gets the complete block device table in linux without resorting to scripts (just one call to lsblk), and adapts it to drivelist-like output.

```
### In addition to the RM flag, any device on the USB or MMC bus must be removable. 
uDev is actually really bad at recognizing this, and often marks MMCs as non-removable.
###
rxRemovable = /(?:^|\:)(?:mmc|usb)(?:\:|$)/

### translates from lsblk's output into drivelist's expected output ###
Drive = (device, parent) ->
    {
        device: device.name,
        size: device.size,
        mountpoint: device.mountpoint,
        ### in the linux scripts, drive.name and drive.device MUST be the same.  Why?  ###
        name: device.name,
        protected: device.ro == '1'
        system: !(device.rm == '1' || device.hotplug == '1' || rxRemovable.test(device.subsystems)),
        description:
            (device.label || device.model || device.uuid || device.serial) || (parent && (
             parent.label || parent.model || parent.uuid || parent.serial
        ))
    }

getDrivesLinux = (callback) ->
    child_process.exec 'lsblk -a -p -J -O -b', (error, stdout, stderr) ->
        return callback(error) if error?

        if not _.str.isBlank(stderr)
            return callback(new Error(stderr))

        ###
        lsblk incorrectly uses '\xHH' for escaping quotes in its JSON output.
        Incorrectly, as \x is not part of JSON.
        This replaces those with the \uCCCC equivalent, which is totes OK in JSON.
        ###

        stdout = stdout.replace(/\\x(\d{2})/g, '\\u00$1')
        devices = JSON.parse(stdout)
        ###
        Structure of lsblk -J output:
        {
            blockdevices: [
                { /* ... block device ... */
                    children: {
                        /* ... partition ... */
                    }
                }
            ]
        }
        ###
        return callback(new Error("Couldn't read block devices"), null) if !devices.blockdevices
        devices = devices.blockdevices
        drives = []
        devices.forEach (device) ->
            ### 
            a block device without a recognizable filesystem (e.g., with partition table)
            is not a drive, but raw device filesystems (e.g., no partition table) are a 
            reasonably common thing, especially in USB drives and SD cards. So we 
            try to make a drive object for both, skipping those without an fstype.
            ###
            drives.push Drive(device) if device.fstype?
            return if !device.children
            device.children.forEach (partition) ->
                drives.push Drive(partition, device) if partition.fstype?
        callback(null, drives)
```

**Comment by Fordi** [comment]
To be fair, `lsblk -J` has only been around since last November - probably wasn't on your radar back when linux.sh was written.

**Comment by jviotti** [comment]
Hi @Fordi ,

Thanks a lot for the feedback. We are *intentionally* omitting the partitions since this module is only concerned with listing the available top-level drives. I suggest using `drivelist` to detect the available drives, and then use custom code in your application around it to fetch the partitions.

That being said, I'm happy to take a PR that extends the drive objects with a `partition` property including the partitions as an object array, however notice this should be implemented for all supported operating systems.

**Comment by Fordi** [comment]
If that's the case, why bother including mountpoints at all?  You don't mount a top-level drive except in very specific cases (like some, but not all USB drives).

I'll fork and work on getting Linux/Windows implementations working in-place, but I'm going to need an assist for Darwin; I don't have a mac to develop against.

**Comment by jviotti** [comment]
Hi @Fordi ,

> If that's the case, why bother including mountpoints at all? You don't mount a top-level drive except in very specific cases (like some, but not all USB drives).

Yeah, the mount points are mainly informative. We just use them in Etcher (https://github.com/resin-io/etcher) as a way for users to quickly check if they are selecting the correct drive.

> I'll fork and work on getting Linux/Windows implementations working in-place, but I'm going to need an assist for Darwin; I don't have a mac to develop against.

Sounds good. Happy to help with OS X.

**Comment by lurch** [comment]
Seems like #85, #69 and #98 are all asking for the same thing? I.e. more detailed information about which specific partition maps to a specific mountpoint.

I guess this could be accomplished by extending my suggestion in https://github.com/resin-io-modules/drivelist/issues/98#issuecomment-257262289 to make `mountpoints` return a dictionary instead of a list? E.g.
```javascript
[
  {
    device: '/dev/sda',
    mountpoints: {
      '/': { partition: '/dev/sda1', size: 12345 },
      '/usr': { partition: '/dev/sda2', size: 678910 },
    },
    ...
  }
]
```

However I wonder if the people making these requests might also be looking for the information about **all** partitions on a drive, regardless of whether they're mounted or not? @Fordi @feliupe @squirrelpiles
IMHO that'd be outside the current scope of this 'drivelist' module.

**Comment by jviotti** [comment]
@lurch I agree with this change. This hasn't been a priority for any of the resin.io products making use of this module, which is the only reason it has been pushed aside for now.

> Seems like #85, #69 and #98 are all asking for the same thing? I.e. more detailed information about which specific partition maps to a specific mountpoint.

I'll close most of them to keep a single source of truth for discussion this feature.

Since changing the format of `mountpoint` is a breaking change, I suggest starting with the following:

```json
[
  {
    "device": "/dev/sda",
    "mountpoints": [
      {
        "path": "/dev/sda1"
      },
      {
        "path": "/dev/sda2"
      }
    ],
    ...
  }
]
```

This way of displaying information doesn't add anything we don't have at the moment, while still provides room to keep adding any other valuable information without breaking the interface again.

**Comment by jviotti** [comment]
Closing this in order to continue discussion on https://github.com/resin-io-modules/drivelist/issues/98
